 /*
 * help.h
 *
 *  Created on: 8 Sep 2019
 *      Author: peter
 */

#ifndef __HELP_H
#define __HELP_H
const char *  const __attribute__((section(".rodata")))help[] = {
 "*                        ","* multiply",
 "+                        ","+ add",
 "-                        ","- subtract",
 "/                        ","/ divide",
 "<=                       ","<= less than or equal",
 "<>                       ","<> not equal",
 "=                        ","= equal or asignment",
 "=<                       ","=< less than or equal",
 "=>                       ","=> greater than or equal",
 ">                        ","> greater than",
 ">=                       ",">= greater than or equal",
 ">>                       ",">> right shift",
 "<<                       ","<< left shift",
 "\\                        ","\\ integer divide",
 "^                        ","^ exponent",
 "$                        ","$ string$",
 "%                        ","i% integer%",
 "!                        ","! float!",
 "'                        ","' comment",
 "?                        ","? String$ (PRINT)",
 "@(                       ","@( PRINT @(x,[ y] [, m] ) expression",
 "#INCLUDE                 ","#INCLUDE file$",
 "#MMDEBUG ON              ","#MMDEBUG ON",
 "#MMDEBUG OFF             ","#MMDEBUG OFF",
 "#DEFINE                  ","#DEFINE oldstring, newstring",
 "ABS(                     ","ABS( number )",
 "ACOS(                    ","ACOS( number )",
 "ADC CLOSE                ","ADC CLOSE",
 "ADC FREQUENCY            ","ADC FREQUENCY frequency",
 "ADC OPEN                 ","ADC OPEN frequency,channel1-pin [,channel2-pin] [,channel3-pin] [,interrupt]",
 "ADC START                ","ADC START channel1array!() [,channel2array!()] [,channel3array!()]",
 "ADC TRIGGER              ","ADC TRIGGER channel, level",
 "AND                      ","AND condition AND condition",
 "AND_PIXELS               ","PAGE AND_PIXELS sourcepage1, sourcepage2, destinationpage",
 "ARC                      ","ARC x, y, r1, [r2], rad1, rad2, colour",
 "AS                       ","OPEN fname$ FOR mode AS [#]fnbr | OPEN comspec$ AS [#]fnbr | OPEN comspec$ AS GPS [,tz_offset] [,monitor]",
 "ASC(                     ","ASC( string$ )",
 "ASIN(                    ","ASIN( radians ) ",
 "ATAN2(                   ","ATAN2( y, x )",
 "ATN(                     ","ATN( radians )",
 "AUTOSAVE                 ","AUTOSAVE file$ |  [CRUNCH]",
 "BAUDRATE(                ","BAUDRATE( comm [, timeout] )",
 "BIN$(                    ","BIN$( number [, chars])",
 "BIN2STR$(                ","BIN2STR$(type, value [,BIG])",
 "BITBANG BITSTREAM        ","BITBANG BITSTREAM pinno, n_transitions, array%()",
 "BITBANG WS2812           ","BITBANG WS2812 type, pin, colours%()",
 "BLIT                     ","BLIT x1, y1, x2, y2, w, h [,page] [,orientation]",
 "BLIT CLOSE               ","BLIT CLOSE [#]b",
 "BLIT READ                ","BLIT READ [#]b, x, y, w, h [,pagenumber]",
 "BLIT WRITE               ","BLIT WRITE [#]b, x, y",
 "BOUND(                   ","BOUND(array() [,dimension]",
 "BOX                      ","BOX x, y, w, h [, lw] [,c] [,fill]",
 "CALL                     ","CALL usersubname$ [,usersubparameters,....]",
 "CASE                     ","CASE testexp [[, testexp] ?]",
 "CASE ELSE                ","CASE ELSE",
 "CASE IS                  ","CASE [IS] comparison",
 "CAT                      ","CAT string$1, string$2",
 "CHDIR                    ","CHDIR dir$",
 "CHOICE(                  ","CHOICE(condition, expression, expression)",
 "CHR$(                    ","CHR$( number )",
 "CINT(                    ","CINT( number )",
 "CIRCLE                   ","CIRCLE x, y, r [, lw] [, a] [, colour] [, fill]",
 "CLASSIC CLOSE            ","CONTROLLER CLASSIC CLOSE [n]",
 "CLASSIC OPEN             ","CONTROLLER CLASSIC OPEN [n] [,interrupt [,bitmask] ]",
 "CLASSIC(                 ","CLASSIC(funct, channel)",
 "CLEAR                    ","CLEAR",
 "CLOSE                    ","CLOSE [#]nbr [,[#]nbr] ?",
 "CLS                      ","CLS [colour]",
 "COLOR                    ","COLOR fore [, back]",
 "COLOUR                   ","COLOUR fore [, back]",
 "CONST                    ","CONST id = expression [, id = expression] ...",
 "CONTINUE                 ","CONTINUE",
 "CONTINUE DO              ","CONTINUE DO",
 "CONTINUE FOR             ","CONTINUE FOR",
 "CONTROLLER               ","CONTROLLER option",
 "CONTROLLER CLASSIC CLOSE ","CONTROLLER CLASSIC CLOSE [n]",
 "CONTROLLER CLASSIC OPEN  ","CONTROLLER CLASSIC OPEN [n] [,interrupt [,bitmask] ]",
 "CONTROLLER MOUSE OPEN    ","CONTROLLER MOUSE OPEN [n] [,LEFTBUTTONint] [,RIGHTBUTTONint]",
 "CONTROLLER MOUSE CLOSE   ","CONTROLLER MOUSE CLOSE [n]",
 "CONTROLLER NUMCHUK OPEN  ","CONTROLLER NUNCHUK OPEN [n] [,Zinterrupt [,Cinterrupt] ]",
 "CONTROLLER NUNCHUK CLOSE ","CONTROLLER NUNCHUK CLOSE [n]",
 "COPY                     ","COPY fname1$ TO fname2$",
 "COS(                     ","COS( radians ) ",
 "CPU RESTART              ","CPU RESTART",
 "CSUB                     ","CSUB name [type [, type] ?]",
 "CWD$                     ","CWD$",
 "DAC                      ","DAC n, voltage",
 "DAC START                ","DAC START frequency, DAC1array%() [,DAC2array%()] [,interrupt]",
 "DAC STOP                 ","DAC STOP",
 "DAY$(NOW)                ","DAY$(NOW)",
 "DAY$(DATE$)              ","DAY$(DATE$)",
 "DATE$                    ","DATE$ = 'DD-MM-YY' or 'DD/MM/YY' or string$ =  DATE$",
 "DATETIME$(               ","DATETIME$(n)",
 "DAY$(                    ","DAY$(date$)",
 "DEFINEFONT               ","DEFINEFONT #n",
 "DEG(                     ","DEG( radians )",
 "DHT22                    ","DHT22 pin, tvar, hvar",
 "DIM                      ","DIM [type] decl [,decl]...",
 "DIM FLOAT                ","DIM FLOAT decl [,decl]...",
 "DIM INTEGER              ","DIM INTEGER  decl [,decl]...",
 "DIM STRING               ","DIM STRING decl [,decl]...",
 "DIR$(                    ","DIR$( [fspec [, type ]] )",
 "DISTANCE(                ","DISTANCE( trigger [, echo ] )",
 "DO                       ","DO",
 "DO WHILE                 ","DO WHILE expression",
 "EDIT                     ","EDIT [file$]",
 "ELSE                     ","ELSE",
 "ELSEIF                   ","ELSEIF expression THEN",
 "END                      ","END",
 "END CSUB                 ","END CSUB",
 "END DEFINEFONT           ","END DEFINEFONT",
 "END FUNCTION             ","END FUNCTION",
 "END IF                   ","END IF",
 "END SELECT               ","END SELECT",
 "END SUB                  ","END SUB",
 "ENDIF                    ","ENDIF",
 "EOF(                     ","EOF( [#]nbr )",
 "EPOCH(                   ","EPOCH(DATETIME$ | NOW)",
 "ERASE                    ","ERASE variable [,variable]...",
 "ERROR                    ","ERROR [error_msg$]",
 "EVAL(                    ","EVAL( string$ )",
 "EXECUTE                  ","EXECUTE command$",
 "EXIT                     ","EXIT [DO]",
 "EXIT DO                  ","EXIT DO",
 "EXIT FOR                 ","EXIT FOR",
 "EXIT FUNCTION            ","EXIT FUNCTION",
 "EXIT SUB                 ","EXIT SUB",
 "EXP(                     ","EXP( number )",
 "FIELD$(                  ","FIELD$( string1, nbr, string2 [, string3] )",
 "FILES                    ","FILES",
 "FIX(                     ","FIX( number )",
 "FONT                     ","FONT [#]font-number, scaling",
 "FOR                      ","FOR counter = start TO finish [STEP increment]",
 "FORMAT$(                 ","FORMAT$( nbr [, fmt$] )",
 "FRAMEBUFFER              ","FRAMEBUFFER option",
 "FRAMEBUFFER BACKUP       ","FRAMEBUFFER BACKUP",
 "FRAMEBUFFER CLOSE        ","FRAMEBUFFER CLOSE",
 "FRAMEBUFFER CREATE       ","FRAMEBUFFER CREATE HorizontalSize%, VerticalSize%",
 "FRAMEBUFFER RESTORE      ","FRAMEBUFFER RESTORE [x, y, w, h]",
 "FRAMEBUFFER WINDOW       ","FRAMEBUFFER WINDOW x, y, page [,I or B]",
 "FRAMEBUFFER WRITE        ","FRAMEBUFFER WRITE",
 "FUNCTION                 ","FUNCTION xxx (arg1 [,arg2, ...]) [AS <type>]",
 "GETSCANLINE              ","GETSCANLINE",
 "GOSUB                    ","GOSUB target",
 "GOTO                     ","GOTO target",
 "GPS(                     ","GPS(option)",
 "GPS(ALTITUDE             ","GPS(ALTITUDE)",
 "GPS(DATE                 ","GPS(DATE)",
 "GPS DOP                  ","GPS(DOP)",
 "GPS(FIX                  ","GPS(FIX)",
 "GPS(GEOID                ","GPS(GEOID)",
 "GPS(LATITUDE             ","GPS(LATITUDE)",
 "GPS(LONGITUDE            ","GPS(LONGITUDE)",
 "GPS(SATELLITES           ","GPS(SATELLITES)",
 "GPS(SPEED                ","GPS(SPEED)",
 "GPS(TIME                 ","GPS(TIME)",
 "GPS(TRACK                ","GPS(TRACK)",
 "GPS(VALID                ","GPS(VALID)",
 "GUI                      ","GUI option",
 "GUI CURSOR ON            ","GUI CURSOR ON [cursorno] [x, y] [cursorcolour]",
 "GUI CURSOR               ","GUI CURSOR x, y",
 "GUI CURSOR OFF           ","GUI CURSOR OFF",
 "GUI CURSOR HIDE          ","GUI CURSOR HIDE",
 "GUI CURSOR SHOW          ","GUI CURSOR SHOW",
 "HELP                     ","HELP",
 "HEX$(                    ","HEX$( number [, chars])",
 "I2C CLOSE                ","I2C CLOSE",
 "I2C OPEN                 ","I2C OPEN speed, timeout",
 "I2C READ                 ","I2C READ addr, option, rcvlen, rcvbuf",
 "I2C WRITE                ","I2C WRITE addr, option, sendlen, send [,sen ...]",
 "I2C2 CLOSE               ","I2C2 CLOSE",
 "I2C2 OPEN                ","I2C2 OPEN speed, timeout",
 "I2C2 READ                ","I2C2 READ addr, option, rcvlen, rcvbuf",
 "I2C2 WRITE               ","I2C2 WRITE addr, option, sendlen, send [,sen ...]",
 "I2C3 CLOSE               ","I2C3 CLOSE",
 "I2C3 OPEN                ","I2C3 OPEN speed, timeout",
 "I2C3 READ                ","I2C3 READ addr, option, rcvlen, rcvbuf",
 "I2C3 WRITE               ","I2C3 WRITE addr, option, sendlen, send [,sen ...]",
 "IF                       ","IF expr THEN stmt [: stmt]",
 "IMAGE                    ","IMAGE option",
 "IMAGE RESIZE             ","IMAGE RESIZE x, y, width, height, new_x, new_y, new_width, new_height [,page_number]",
 "IMAGE RESIZE_FAST        ","IMAGE RESIZE_FAST x, y, width, height, new_x, new_y, new_width, new_height [,page_number] [,flag]",
 "IMAGE ROTATE             ","IMAGE ROTATE x, y, width, height, new_x, new_y, angle! [,page_number]",
 "IMAGE ROTATE_FAST        ","IMAGE ROTATE_FAST x, y, width, height, new_x, new_y, angle! [,page_number] [,flag]",
 "IMAGE WARP_H             ","IMAGE WARP_H x, y, w, h, x1, y1, h1, x2, y2, h2 [,readpage] [,dontcopyblack]",
 "IMAGE WARP_V             ","IMAGE WARP_V x, y, w, h, x1, y1, w1, x2, y2, w2 [,readpage] [,dontcopyblack]",
 "INC                      ","INC var [,increment]",
 "INKEY$                   ","INKEY$",
 "INPUT                    ","INPUT ['prompt$';] var1 [,var2 [, var3 ...]] or INPUT #nbr, list of variables",
 "INPUT$(                  ","INPUT$(nbr, [#]fnbr)",
 "INSTR(                   ","INSTR( [start-position,] stringsearched$, string-pattern$ )",
 "INT(                     ","INT( number )",
 "INV                      ","INV expression",
 "IR                       ","IR dev, key , int",
 "IR CLOSE                 ","IR CLOSE",
 "IR SEND                  ","IR SEND pin, dev, key",
 "IRETURN                  ","IRETURN",
 "KEYDOWN(                 ","KEYDOWN(n)",
 "KILL                     ","KILL file$",
 "LCASE$(                  ","LCASE$( string$ )",
 "LCOMPARE(                ","LCOMPARE(array1%(), array2%())",
 "LEFT$(                   ","LEFT$( string$, nbr )",
 "LEN(                     ","LEN( string$ )",
 "LET                      ","LET variable = expression",
 "LGETBYTE(                ","LGETBYTE(array%(), n)",
 "LGETSTR$(                ","LGETSTR$(array%(), start, length)",
 "LINE                     ","LINE x1, y1, x2, y2 [, LW [, C]]",
 "LINE INPUT               ","LINE INPUT [prompt$,] string-variable$",
 "LINPUT(                  ","LINPUT(array%(), fnbr ,nbr)",
 "LINSTR(                  ","LINSTR(array%(), search$ [,start])",
 "LIST                     ","LIST [file$]",
 "LIST ALL                 ","LIST ALL [file$]",
 "LIST COMMANDS            ","LIST COMMANDS",
 "LIST FILES               ","LIST FILES [fspec$] [, sort]",
 "LIST FUNCTIONS           ","LIST FUNCTIONS",
 "LIST PAGES               ","LIST PAGES",
 "LLEN(                    ","LLEN(array%())",
 "LMID(                    ","LMID(array%(),start [,num])=string$",
 "LOAD BMP                 ","LOAD BMP file$ [, x, y]",
 "LOAD FONT                ","LOAD FONT file$",
 "LOAD GIF                 ","LOAD GIF [file$ [, x, y]]",
 "LOAD JPG                 ","LOAD JPG file$ [, x, y]",
 "LOAD PNG                 ","LOAD PNG file$ [, x, y] [, transparency_cut_off]",
 "LOC(                     ","LOC( [#]fnbr )",
 "LOCAL                    ","LOCAL variable [, variables]",
 "LOCAL FLOAT              ","LOCAL FLOAT variable [, variables]",
 "LOCAL INTEGER            ","LOCAL INTEGER variable [, variables]",
 "LOCAL STRING             ","LOCAL STRING variable [, variables]",
 "LOF(                     ","LOF( [#]fnbr )",
 "LOG(                     ","LOG( number )",
 "LONGSTRING               ","LONGSTRING option",
 "LONGSTRING APPEND        ","LONGSTRING APPEND array%(), string$",
 "LONGSTRING CLEAR         ","LONGSTRING CLEAR array%()",
 "LONGSTRING CONCAT        ","LONGSTRING CONCAT dest%(), src%()",
 "LONGSTRING COPY          ","LONGSTRING COPY dest%(), src%()",
 "LONGSTRING LCASE         ","LONGSTRING LCASE array%()",
 "LONGSTRING LEFT          ","LONGSTRING LEFT dest%(), src%(), nbr",
 "LONGSTRING LOAD          ","LONGSTRING LOAD array%(), nbr, string$",
 "LONGSTRING MID           ","LONGSTRING MID dest%(), src%(), start, nbr",
 "LONGSTRING PRINT         ","LONGSTRING PRINT [#n,] src%()",
 "LONGSTRING REPLACE       ","LONGSTRING REPLACE array%() , string$, start",
 "LONGSTRING RESIZE        ","LONGSTRING RESIZE n",
 "LONGSTRING RIGHT         ","LONGSTRING RIGHT dest%(), src%(), nbr",
 "LONGSTRING SETBYTE       ","LONGSTRING SETBYTE  , n",
 "LONGSTRING TRIM          ","LONGSTRING TRIM array%(), nbr",
 "LONGSTRING UCASE         ","LONGSTRING UCASE array%()",
 "LOOP                     ","LOOP [UNTIL expression]",
 "LOOP UNTIL               ","LOOP [UNTIL expression]",
 "LS                       ","LS",
 "MAP MAXIMITE             ","MAP MAXIMITE",
 "MAP RESET                ","MAP RESET",
 "MAP SET                  ","MAP SET",
 "MAP(                     ","MAP( n ) = rgb%",
 "MATH ADD                 ","MATH ADD in(), num, out()",
 "MATH FFT                 ","MATH FFT signalarray!(), FFTarray!()",
 "MATH FFT INVERSE         ","MATH FFT INVERSE FFTarray!(), signalarray!()",
 "MATH FFT MAGNITUDE       ","MATH FFT MAGNITUDE signalarray!(),magnitudearray!()",
 "MATH FFT PHASE           ","MATH FFT PHASE signalarray!(), phasearray!()",
 "MATH INSERT              ","MATH INSERT targetarray(), [d1] [,d2] [,d3] [,d4] [,d5] , sourcearray()",
 "MATH M_MULT              ","MATH M_MULT in1(), in2(), out()",
 "MATH M_PRINT             ","MATH M_PRINT array()",
 "MATH M_TRANSPOSE         ","MATH M_TRANSPOSE in(), out()",
 "MATH Q_CREATE            ","MATH Q_CREATE theta, x, y, z, outRQ()",
 "MATH Q_INVERT            ","MATH Q_INVERT inQ(), outQ()",
 "MATH Q_MULT              ","MATH Q_MULT inQ1(), inQ2(), outQ()",
 "MATH Q_ROTATE            ","MATH Q_ROTATE RQ(), inVQ(), outVQ()",
 "MATH Q_VECTOR            ","MATH Q_VECTOR x, y, z, outVQ()",
 "MATH SCALE               ","MATH SCALE in(), scale ,out()",
 "MATH SET                 ","MATH SET nbr, array()",
 "MATH SLICE               ","MATH SLICE sourcearray(), [d1] [,d2] [,d3] [,d4] [,d5] , destinationarray()",
 "MATH V_CROSS             ","MATH V_CROSS inV1(), inV2(), outV()",
 "MATH V_MULT              ","MATH V_MULT matrix(), inV(), outV()",
 "MATH V_NORMALISE         ","MATH V_NORMALISE inV(), outV()",
 "MATH V_PRINT             ","MATH V_PRINT array()",
 "MATH(ATAN3               ","MATH(ATAN3 x,y)",
 "MATH(CHI                 ","MATH(CHI a())",
 "MATH(CHI_p               ","MATH(CHI_p a())",
 "MATH(COSH                ","MATH(COSH a)",
 "MATH(DOTPRODUCT          ","MATH(DOTPRODUCT v1(), v2()",
 "MATH(LOG10               ","MATH(LOG10 a)",
 "MATH(MAGNITUDE           ","MATH(MAGNITUDE v())",
 "MATH(MAX                 ","MATH(MAX a())",
 "MATH(MEAN                ","MATH(MEAN a())",
 "MATH(MEDIAN              ","MATH(MEDIAN a())",
 "MATH(MIN                 ","MATH(MIN a())",
 "MATH(SD                  ","MATH(SD a())",
 "MATH(SINH                ","MATH(SINH a)",
 "MATH(SUM                 ","MATH(SUM a())",
 "MATH(TANH                ","MATH(TANH a)",
 "MAX(                     ","MAX( arg1 [, arg2 [, ?]] )",
 "MEMORY                   ","MEMORY",
 "MEMORY COPY              ","MEMORY COPY sourceaddress%, destinationaddres%, numberofbytes%",
 "MEMORY SET               ","MEMORY SET address%, byte%, numberofbytes%",
 "MEMORY SET BYTE          ","MEMORY SET BYTE address%, byte%, numberofbytes%",
 "MEMORY SET SHORT         ","MEMORY SET SHORT address%, short%, numberofshorts%",
 "MEMORY SET WORD          ","MEMORY SET WORD address%, word%, numberofwords%",
 "MEMORY SET INTEGER       ","MEMORY SET INTEGER address%, integer%, numberofintegers%",
 "MEMORY SET FLOAT         ","MEMORY SET FLOAT address%, float!, numberoffloats%",
 "MID$(                    ","MID$( str$, start [, num]) = str2$ or str2$ =  MID$( string$, start [, nbr]  )",
 "MIN(                     ","MIN( arg1 [, arg2 [, ?]] )",
 "MKDIR                    ","MKDIR dir$",
 "MM.CMDLINE$              ","MM.CMDLINE$",
 "MM.DEVICE$               ","MM.DEVICE$",
 "MM.ERRMSG$               ","MM.ERRMSG$",
 "MM.ERRNO                 ","MM.ERRNO",
 "MM.FONTHEIGHT            ","MM.FONTHEIGHT ",
 "MM.FONTWIDTH             ","MM.FONTWIDTH",
 "MM.HRES                  ","MM.HRES",
 "MM.I2C                   ","MM.I2C",
 "MM.INFO$(CPUSPEED        ","MM.INFO$( CPUSPEED)",
 "MM.INFO$(CURRENT         ","MM.INFO$( CURRENT)",
 "MM.INFO$(KEYBOARD        ","MM.INFO$( KEYBOARD)",
 "MM.INFO$(MODIFIED        ","MM.INFO$(MODIFIED file$)",
 "MM.INFO$(OPTION AUTORUN  ","MM.INFO$( OPTION AUTORUN)",
 "MM.INFO$(PIN             ","MM.INFO$(PIN pinno)",
 "MM.INFO$(SDCARD          ","MM.INFO$( SDCARD)",
 "MM.INFO$(SEARCH PATH     ","MM.INFO$( SEARCH PATH)",
 "MM.INFO$(SOUND           ","MM.INFO$( SOUND)",
 "MM.INFO$(TRACK           ","MM.INFO$( TRACK)",
 "MM.INFO(DISK SIZE        ","MM.INFO( DISK SIZE)",
 "MM.INFO(FILESIZE         ","MM.INFO(FILESIZE file$)",
 "MM.INFO(FONTHEIGHT       ","MM.INFO( FONTHEIGHT)",
 "MM.INFO(FONTWIDTH        ","MM.INFO( FONTWIDTH)",
 "MM.INFO(FRAMEH           ","MM.INFO( FRAMEH)",
 "MM.INFO(FRAMEV           ","MM.INFO( FRAMEV)",
 "MM.INFO(FREE SPACE       ","MM.INFO( FREE SPACE)",
 "MM.INFO(HPOS             ","MM.INFO( HPOS)",
 "MM.INFO(MAX PAGES        ","MM.INFO( MAX PAGES)",
 "MM.INFO(MODE             ","MM.INFO( MODE)",
 "MM.INFO(OPTION           ","MM.INFO(OPTION option)",
 "MM.INFO(PAGE ADDRESS     ","MM.INFO(PAGE ADDRESS n)",
 "MM.INFO(PROGRAM          ","MM.INFO( PROGRAM)",
 "MM.INFO(RESET            ","MM.INFO(RESET)",
 "MM.INFO(VERSION          ","MM.INFO( VERSION)",
 "MM.INFO(VPOS             ","MM.INFO( VPOS)",
 "MM.INFO(WRITE PAGE       ","MM.INFO( WRITE PAGE)",
 "MM.ONEWIRE               ","MM.ONEWIRE",
 "MM.VER                   ","MM.VER ",
 "MM.VRES                  ","MM.VRES",
 "MM.WATCHDOG              ","MM.WATCHDOG",
 "MMDEBUG                  ","MMDEBUG",
 "MOD                      ","MOD value MOD value",
 "MODE                     ","MODE r, bits [, bg [, int]]",
 "MOUSE(                   ","MOUSE( function [,i2channel])",
 "NEW                      ","NEW",
 "NEXT                     ","NEXT [counter-variable] [, counter-variable], etc",
 "NOT                      ","NOT expression",
 "NUNCHUK(                 ","NUNCHUK(funct, channel)",
 "OCT$(                    ","OCT$( number [, chars])",
 "ON                       ","ON nbr GOTO | GOSUB target1 [, target2, ...]",
 "ON ERROR ABORT           ","ON ERROR ABORT",
 "ON ERROR CLEAR           ","ON ERROR CLEAR",
 "ON ERROR IGNORE          ","ON ERROR IGNORE",
 "ON ERROR SKIP            ","ON ERROR SKIP [nn]",
 "ON KEY                   ","ON KEY [ASCIIcode,] interrupt_routine",
 "ONEWIRE READ             ","ONEWIRE READ pin, flag, length,  [,  ...]",
 "ONEWIRE RESET            ","ONEWIRE RESET pin",
 "ONEWIRE WRITE            ","ONEWIRE WRITE pin, flag, length,  [,  ...]",
 "OPEN                     ","OPEN fname$ FOR mode AS [#]fnbr | OPEN comspec$ AS [#]fnbr | OPEN comspec$ AS GPS [,tz_off] [,monitor]",
 "OPTION ANGLE             ","OPTION ANGLE mode",
 "OPTION AUTORUN           ","OPTION AUTORUN OFF | ON",
 "OPTION BASE              ","OPTION BASE 0 | 1",
 "OPTION BAUDRATE          ","OPTION BAUDRATE nbr",
 "OPTION BREAK             ","OPTION BREAK nn",
 "OPTION CASE              ","OPTION CASE UPPER | LOWER | TITLE",
 "OPTION CLOCKTRIM         ","OPTION CLOCKTRIM ?n",
 "OPTION COLOURCODE        ","OPTION COLOURCODE ON | OFF | REVERSE",
 "OPTION CONSOLE           ","OPTION CONSOLE SCREEN | SERIAL | BOTH or OPTION CONSOLE SAVE",
 "OPTION CONSOLE AUTO      ","OPTION CONSOLE AUTO",
 "OPTION CONSOLE ECHO      ","OPTION CONSOLE ECHO | NOECHO",
 "OPTION CONSOLE INVERT    ","OPTION CONSOLE INVERT | NOINVERT",
 "OPTION CONTROLS          ","OPTION CONTROLS nn",
 "OPTION CRLF              ","OPTION CRLF CR | LF | CRLF",
 "OPTION DEFAULT           ","OPTION DEFAULT FLOAT | INTEGER | STRING | NONE",
 "OPTION DEFAULT MODE      ","OPTION DEFAULT MODE n",
 "OPTION DISPLAY           ","OPTION DISPLAY lines [,chars]",
 "OPTION EDIT FONT         ","OPTION EDIT FONT SMALL | NORMAL | MEDIUM | LARGE",
 "OPTION EXPLICIT          ","OPTION EXPLICIT",
 "OPTION F11               ","OPTION F11 string$",
 "OPTION F12               ","OPTION F12 string$",
 "OPTION FLASH             ","OPTION FLASH [n]",
 "OPTION KEYBOARD REPEAT   ","OPTION KEYBOARD REPEAT firstchar, nextchar",
 "OPTION LCDPANEL          ","OPTION LCDPANEL options",
 "OPTION LEGACY            ","OPTION LEGACY ON | OFF",
 "OPTION LIST              ","OPTION LIST",
 "OPTION MILLISECONDS      ","OPTION MILLISECONDS ON | OFF",
 "OPTION PIN               ","OPTION PIN nbr",
 "OPTION RAM               ","OPTION RAM",
 "OPTION RESET             ","OPTION RESET",
 "OPTION RTC CALIBRATE     ","OPTION RTC CALIBRATE ?n",
 "OPTION SD TIMING         ","OPTION SD TIMING NORMAL | FAST",
 "OPTION SDCARD            ","OPTION SDCARD CS [, CD [,WP]] | DISABLE",
 "OPTION SEARCH PATH       ","OPTION SEARCH PATH pathname$",
 "OPTION SERIAL PULLUP     ","OPTION SERIAL PULLUP ENABLE | DISABLE",
 "OPTION STATUS            ","OPTION STATUS ON | OFF",
 "OPTION TAB               ","OPTION TAB 2 | 3 | 4 | 8",
 "OPTION USBKEYBOARD       ","OPTION USBKEYBOARD | UK | US | DE | FR | ES [,noLED]",
 "OPTION VCC               ","OPTION VCC voltage",
 "OPTION Y_AXIS            ","OPTION Y_AXIS UP | DOWN",
 "OR                       ","OR value OR value",
 "PAGE AND_PIXELS          ","PAGE AND_PIXELS sourcepage1, sourcepage2, destinationpage",
 "PAGE COPY                ","PAGE COPY n TO m [,when]",
 "PAGE LIST                ","PAGE LIST",
 "PAGE OR_PIXELS           ","PAGE OR_PIXELS sourcepage1, sourcepage2, destinationpage",
 "PAGE RESIZE              ","PAGE RESIZE pageno, width, height",
 "PAGE SCROLL              ","PAGE SCROLL pageno, x, y [,fillcolour]",
 "PAGE STITCH              ","PAGE STITCH frompage1, from_page_2, topage, offset",
 "PAGE WRITE               ","PAGE WRITE n",
 "PAGE XOR_PIXELS          ","PAGE XOR_PIXELS sourcepage1, sourcepage2, destinationpage",
 "PAUSE                    ","PAUSE delay mS",
 "PEEK(BYTE                ","PEEK(BYTE addr%)",
 "PEEK(FLOAT               ","PEEK(FLOAT addr%",
 "PEEK(INTEGER             ","PEEK(INTEGER addr%)",
 "PEEK(PROGMEM             ","PEEK( PROGMEM, ?offset)",
 "PEEK(SHORT               ","PEEK(SHORT addr%)",
 "PEEK(VAR                 ","PEEK(VAR var, ?offset)",
 "PEEK(VARADDR             ","PEEK(VARADDR var)",
 "PEEK(VARHEADER           ","PEEK(VARHEADER var)",
 "PEEK(VARTBL              ","PEEK( VARTBL, ?offset)",
 "PEEK(WORD                ","PEEK(WORD addr%)",
 "PHONETIC                 ","PLAY TTS [PHONETIC] 'text' [,speed] [,pitch] [,mouth] [,throat] [, interrupt]",
 "PI                       ","PI",
 "PIN                      ","PIN( pin | function$)",
 "PIN(                     ","PIN( pin ) = value",
 "PIXEL                    ","PIXEL x, y [,colour]",
 "PIXEL(                   ","PIXEL( x, y [,page_number])",
 "PLAY EFFECT              ","PLAY EFFECT file$ [,interrupt]",
 "PLAY FLAC                ","PLAY FLAC file$ [, interrupt]",
 "PLAY MODFILE             ","PLAY MODFILE file$ [,samplerate]",
 "PLAY MODSAMPLE           ","PLAY MODSAMPLE sampleno, channelno [,volume] [,samplerate]",
 "PLAY MP3                 ","PLAY MP3 file$ [, interrupt]",
 "PLAY NEXT                ","PLAY NEXT",
 "PLAY PAUSE               ","PLAY PAUSE",
 "PLAY PREVIOUS            ","PLAY PREVIOUS",
 "PLAY RESUME              ","PLAY RESUME",
 "PLAY SOUND               ","PLAY SOUND soundno, channelno, type [,frequency] [,volume]",
 "PLAY STOP                ","PLAY STOP",
 "PLAY TONE                ","PLAY TONE left , right [, dur [, interrupt]]",
 "PLAY TTS                 ","PLAY TTS [PHONETIC] 'text' [,speed] [,pitch] [,mouth] [,throat] [, interrupt]",
 "PLAY VOLUME              ","PLAY VOLUME left, right",
 "PLAY WAV                 ","PLAY WAV file$ [, interrupt]",
 "POKE BYTE                ","POKE BYTE addr%, byte",
 "POKE FLOAT               ","POKE FLOAT addr%, float!",
 "POKE INTEGER             ","POKE INTEGER addr%, int%",
 "POKE SHORT               ","POKE SHORT addr%, short%",
 "POKE VAR                 ","POKE VAR var, offset, byte",
 "POKE VARTBL              ","POKE VARTBL, offset, byte",
 "POKE WORD                ","POKE WORD addr%, word%",
 "POLYGON                  ","POLYGON n[()], xarray%(), yarray%() [, bordercolour[()]] [, fillcolour[()]]",
 "PORT(                    ","PORT(start, nbr [,start, nbr] ...) = value or value = PORT(start, nbr [,start, nbr]?)",
 "POS                      ","POS",
 "PRINT                    ","PRINT expression [[,; ]expression] ... | PRINT #nbr, expression [[,; ]expression] ?",
 "PRINT #GPS               ","PRINT #GPS, string$",
 "PRINT @(                 ","PRINT @(x, y [, m] ) expression",
 "PULSE                    ","PULSE pin, width",
 "PULSIN(                  ","pulsewidth = PULSIN( pin, polarity [, t1 [, t2]])",
 "PWM                      ","PWM channel, freq, chA [, chB [, chC ]] | PWM channel, STOP",
 "RAD(                     ","RAD( degrees )",
 "RBOX                     ","RBOX x, y, w, h [, r] [,colour] [,fill]",
 "READ                     ","READ variable[, variable]...",
 "REM                      ","REM text$",
 "RENAME                   ","RENAME old$ AS new$",
 "RESTORE                  ","RESTORE [line]",
 "RETURN                   ","RETURN",
 "RGB(                     ","RGB(red, green, blue [, trans])",
 "RIGHT$(                  ","RIGHT$( string$, number-of-chars)",
 "RMDIR                    ","RMDIR dir$",
 "RND(                     ","RND( [ number ] )",
 "ROTATE                   ","IMAGE ROTATE x, y, width, height, new_x, new_y, angle! [,page_number]",
 "RUN                      ","RUN file$ [, cmdline]",
 "SAVE IMAGE               ","SAVE IMAGE file$ [,x, y, w, h]",
 "SEEK                     ","SEEK [#]fnbr, pos",
 "SELECT                   ","SELECT CASE value",
 "SELECT CASE              ","SELECT CASE value",
 "SERVO                    ","SERVO channel, freq, chA [, chB [, chC ]] | SERVO channel, STOP",
 "SETPIN                   ","SETPIN pin, cfg [, target] [, option]",
 "SETTICK                  ","SETTICK period, target [, nbr]",
 "SGN(                     ","SGN( number )",
 "SIN(                     ","SIN( radians ) ",
 "SORT                     ","SORT array() [,indexarray()]",
 "SPACE$(                  ","SPACE$( number )",
 "SPI CLOSE                ","SPI CLOSE",
 "SPI OPEN                 ","SPI OPEN speed, mode, bits",
 "SPI READ                 ","SPI READ nbr, array()",
 "SPI WRITE                ","SPI WRITE nbr,[ 1, ... | String$ | array() ]",
 "SPI(                     ","SPI(  )",
 "SPI2 CLOSE               ","SPI2 CLOSE",
 "SPI2 OPEN                ","SPI2 OPEN speed, mode, bits",
 "SPI2 READ                ","SPI2 READ nbr, array()",
 "SPI2 WRITE               ","SPI2 WRITE nbr,[ 1, ... | String$ | array() ]",
 "SPI2(                    ","SPI2(  )",
 "SPRITE CLOSE             ","SPRITE CLOSE [#]n",
 "SPRITE CLOSE ALL         ","SPRITE CLOSE ALL",
 "SPRITE COPY              ","SPRITE COPY [#]n, [#]m, nbr",
 "SPRITE HIDE              ","SPRITE HIDE [#]n",
 "SPRITE HIDE ALL          ","SPRITE HIDE ALL",
 "SPRITE HIDE SAFE         ","SPRITE HIDE SAFE [#]n",
 "SPRITE INTERRUPT         ","SPRITE INTERRUPT sub",
 "SPRITE LOAD              ","SPRITE LOAD fname$ [,start_sprite_number]",
 "SPRITE LOADARRAY         ","SPRITE LOADARRAY [#]n, w, h, array%()",
 "SPRITE LOADPNG           ","SPRITE LOADPNG [#]n, fname$ [, transparency_cut_off]",
 "SPRITE MOVE              ","SPRITE MOVE",
 "SPRITE NEXT              ","SPRITE NEXT [#]n, x, y",
 "SPRITE NOINTERUPT        ","SPRITE NOINTERRUPT",
 "SPRITE READ              ","SPRITE READ [#]n, x , y, w, h [,pagenumber]",
 "SPRITE RESTORE           ","SPRITE RESTORE",
 "SPRITE SCROLL            ","SPRITE SCROLL x, y [,col]",
 "SPRITE SCROLLR           ","SPRITE SCROLLR x, y, w, h, delta_x, delta_y [,col]",
 "SPRITE SHOW              ","SPRITE SHOW [#]n, x,y, layer, [orientation]",
 "SPRITE SHOW SAFE         ","SPRITE SHOW SAFE [#]n, x,y, layer [,orientation] [,ontop]",
 "SPRITE SWAP              ","SPRITE SWAP [#]n1, [#]n2 [,orientation]",
 "SPRITE TRANSPARENCY      ","SPRITE TRANSPARENCY [#]n, transparency",
 "SPRITE WRITE             ","SPRITE WRITE [#]n, x y",
 "SPRITE(C                 ","SPRITE(C, [#]n [, m ])",
 "SPRITE(D                 ","SPRITE(D, ,spriteno1, spriteno2)",
 "SPRITE(E                 ","SPRITE(E,spriteno)",
 "SPRITE(H                 ","SPRITE(H,[#]n)",
 "SPRITE(L                 ","SPRITE(L, [#]n)",
 "SPRITE(N                 ","SPRITE(N [,n ])",
 "SPRITE(S                 ","SPRITE(S)",
 "SPRITE(T                 ","SPRITE(T,spriteno)",
 "SPRITE(V                 ","SPRITE(V,spriteno1,spriteno2)",
 "SPRITE(W                 ","SPRITE(W, [#]n)",
 "SPRITE(X                 ","SPRITE(X, [#]n)",
 "SPRITE(Y                 ","SPRITE(Y, [#]n)",
 "SQR(                     ","SQR( number )",
 "STATIC                   ","STATIC variable [, variables]",
 "STATIC FLOAT             ","STATIC FLOAT variable [, variables]",
 "STATIC INTEGER           ","STATIC INTEGER variable [, variables]",
 "STATIC STRING            ","STATIC STRING variable [, variables]",
 "STEP                     ","FOR counter = start TO finish [STEP increment]",
 "STR$(                    ","STR$( number [, m [, n [, c$ ]]]  )",
 "STR2BIN(                 ","STR2BIN(type, string$ [,BIG])",
 "STRING$(                 ","STRING$( nbr, ascii | string$ )",
 "SUB                      ","SUB xxx (arg1 [,arg2, ?])",
 "TAB(                     ","TAB( number )",
 "TAN(                     ","TAN( radians ) ",
 "TEMPR START              ","TEMPR START pin [, precision]",
 "TEMPR(                   ","TEMPR( pin )",
 "TEXT                     ","TEXT x, y, string$ [,alignment$] [, font] [, scale] [, colour] [, bc]",
 "THEN                     ","IF expr THEN stmt [: stmt]",
 "TIME$                    ","TIME$ = 'HH:MM:SS'  | TIME$ = ?sec or string$ = TIME$",
 "TIMER                    ","TIMER = msec or value = TIMER",
 "TO                       ","TO FOR counter = start TO finish [STEP increment]",
 "TRACE                    ","TRACE option",
 "TRACE LIST               ","TRACE LIST nn",
 "TRACE OFF                ","TRACE OFF",
 "TRACE ON                 ","TRACE ON",
 "TRIANGLE                 ","TRIANGLE X1, Y1, X2, Y2, X3, Y3 [, Colour [, FILL]]",
 "TURTLE BACKWARD          ","TURTLE BACKWARD n",
 "TURTLE BEGIN FILL        ","TURTLE BEGIN FILL",
 "TURTLE DOT               ","TURTLE DOT",
 "TURTLE DRAW CIRCLE       ","TURTLE DRAW CIRCLE x, y, r",
 "TURTLE DRAW LINE         ","TURTLE DRAW LINE x1, y1, x2, y2",
 "TURTLE DRAW PIXEL        ","TURTLE DRAW PIXEL x, y",
 "TURTLE DRAW TURTLE       ","TURTLE DRAW TURTLE",
 "TURTLE END FILL          ","TURTLE END FILL",
 "TURTLE FILL COLOUR       ","TURTLE FILL COLOUR col",
 "TURTLE FILL PIXEL        ","TURTLE FILL PIXEL x, y",
 "TURTLE FORWARD           ","TURTLE FORWARD n",
 "TURTLE HEADING           ","TURTLE HEADING deg",
 "TURTLE MOVE              ","TURTLE MOVE x, y",
 "TURTLE PEN DOWN          ","TURTLE PEN DOWN",
 "TURTLE PEN UP            ","TURTLE PEN UP",
 "TURTLE RESET             ","TURTLE RESET",
 "TURTLE TURN LEFT         ","TURTLE TURN LEFT deg",
 "TURTLE TURN RIGHT        ","TURTLE TURN RIGHT deg",
 "TUTTLE PEN COLOUR        ","TURTLE PEN COLOUR col",
 "UCASE$(                  ","UCASE$( string$ )",
 "UNTIL                    ","LOOP UNTIL expression",
 "UPDATE FIRMWARE          ","UPDATE FIRMWARE",
 "VAL(                     ","VAL( string$ )",
 "VAR CLEAR                ","VAR CLEAR",
 "VAR RESTORE              ","VAR RESTORE",
 "VAR SAVE                 ","VAR SAVE var [, var] ?",
 "WATCHDOG                 ","WATCHDOG timeout | OFF",
 "WII CLASSIC CLOSE        ","WII CLASSIC CLOSE [n]",
 "WII CLASSIC OPEN         ","WII CLASSIC OPEN [n] [,interrupt [,bitmask] ]",
 "WII MOUSE OPEN           ","WII MOUSE OPEN [n] [,LEFTBUTTONint] [,RIGHTBUTTONint]",
 "WII MOUSE CLOSE          ","WII MOUSE CLOSE [n]",
 "WII NUMCHUK OPEN         ","WII NUNCHUK OPEN [n] [,Zinterrupt [,Cinterrupt] ]",
 "WII NUNCHUK CLOSE        ","WII NUNCHUK CLOSE [n]",
 "XMODEM RECEIVE           ","XMODEM RECEIVE [CRUNCH] file$",
 "XMODEM SEND              ","XMODEM SEND file$",
 "XOR                      ","XOR value XOR value",
 "Z                        ","                ",
 "Z                        ","                ",
 "Z                        ","                ",
 "Z                        ","                "
 };
#endif
